services:
  wol-backend:
    environment:
      TOKEN_EXPIRES_SECONDS: ${TOKEN_EXPIRES_SECONDS:-28800}
      ENFORCE_IP_ALLOWLIST: ${ENFORCE_IP_ALLOWLIST:-true}
      TRUST_PROXY_HEADERS: ${TRUST_PROXY_HEADERS:-false}
    volumes:
      - wol-data-testing:/data

volumes:
  wol-data-testing:
